//Verilog generated by VPR 8.1.0-dev+v8.0.0-10951-g49de5fb78 from post-place-and-route implementation
module ripple_carry_adder_8bit (
    input \a~0 ,
    input \rst ,
    input \clk ,
    input \b~6 ,
    input \b~1 ,
    input \a~2 ,
    input \b~4 ,
    input \b~3 ,
    input \a~6 ,
    input \b~2 ,
    input \a~5 ,
    input \cin ,
    input \a~4 ,
    input \b~7 ,
    input \a~7 ,
    input \a~1 ,
    input \a~3 ,
    input \b~0 ,
    input \b~5 ,
    output \sum~7 ,
    output \sum~2 ,
    output \cout ,
    output \sum~3 ,
    output \sum~5 ,
    output \sum~4 ,
    output \sum~0 ,
    output \sum~1 ,
    output \sum~6 
);

    //Wires
    wire \a~0_output_0_0 ;
    wire \rst_output_0_0 ;
    wire \clk_output_0_0 ;
    wire \b~6_output_0_0 ;
    wire \b~1_output_0_0 ;
    wire \a~2_output_0_0 ;
    wire \b~4_output_0_0 ;
    wire \b~3_output_0_0 ;
    wire \a~6_output_0_0 ;
    wire \b~2_output_0_0 ;
    wire \a~5_output_0_0 ;
    wire \cin_output_0_0 ;
    wire \a~4_output_0_0 ;
    wire \b~7_output_0_0 ;
    wire \a~7_output_0_0 ;
    wire \a~1_output_0_0 ;
    wire \a~3_output_0_0 ;
    wire \b~0_output_0_0 ;
    wire \b~5_output_0_0 ;
    wire \latch_sum~7_output_0_0 ;
    wire \latch_sum~2_output_0_0 ;
    wire \latch_cout_output_0_0 ;
    wire \latch_sum~3_output_0_0 ;
    wire \latch_sum~5_output_0_0 ;
    wire \latch_sum~4_output_0_0 ;
    wire \latch_sum~0_output_0_0 ;
    wire \latch_sum~1_output_0_0 ;
    wire \latch_sum~6_output_0_0 ;
    wire \lut_n145_1_output_0_0 ;
    wire \lut_n149_1_output_0_0 ;
    wire \lut_n153_1_output_0_0 ;
    wire \lut_n157_1_output_0_0 ;
    wire \lut_n161_1_output_0_0 ;
    wire \lut_n165_1_output_0_0 ;
    wire \lut_n169_1_output_0_0 ;
    wire \lut_n173_1_output_0_0 ;
    wire \lut_n177_1_output_0_0 ;
    wire \adder_$add~2^ADD~8-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~2^ADD~8-1[1]_output_1_0 ;
    wire \adder_$add~2^ADD~8-1[1]_output_0_0 ;
    wire \lut_gnd_output_0_0 ;
    wire \adder_$add~2^ADD~8-2[1]_output_1_0 ;
    wire \lut_vcc_output_0_0 ;
    wire \adder_$add~4^ADD~9-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~4^ADD~9-1[1]_output_1_0 ;
    wire \adder_$add~4^ADD~9-1[1]_output_0_0 ;
    wire \adder_$add~4^ADD~9-2[1]_output_1_0 ;
    wire \adder_$add~6^ADD~10-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~6^ADD~10-1[1]_output_1_0 ;
    wire \adder_$add~6^ADD~10-1[1]_output_0_0 ;
    wire \adder_$add~6^ADD~10-2[1]_output_1_0 ;
    wire \adder_$add~8^ADD~11-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~8^ADD~11-1[1]_output_1_0 ;
    wire \adder_$add~8^ADD~11-1[1]_output_0_0 ;
    wire \adder_$add~8^ADD~11-2[1]_output_1_0 ;
    wire \adder_$add~10^ADD~12-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~10^ADD~12-1[1]_output_1_0 ;
    wire \adder_$add~10^ADD~12-1[1]_output_0_0 ;
    wire \adder_$add~10^ADD~12-2[1]_output_1_0 ;
    wire \adder_$add~12^ADD~13-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~12^ADD~13-1[1]_output_1_0 ;
    wire \adder_$add~12^ADD~13-1[1]_output_0_0 ;
    wire \adder_$add~12^ADD~13-2[1]_output_1_0 ;
    wire \adder_$add~14^ADD~14-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~14^ADD~14-1[1]_output_1_0 ;
    wire \adder_$add~14^ADD~14-1[1]_output_0_0 ;
    wire \adder_$add~14^ADD~14-2[1]_output_1_0 ;
    wire \adder_$add~16^ADD~15-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~16^ADD~15-1[1]_output_1_0 ;
    wire \adder_$add~16^ADD~15-1[1]_output_0_0 ;
    wire \adder_$add~16^ADD~15-2[1]_output_1_0 ;
    wire \adder_$add~17^ADD~0-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~15^ADD~1-2[1]_output_1_0 ;
    wire \adder_$add~17^ADD~0-1[1]_output_1_0 ;
    wire \adder_$add~17^ADD~0-1[1]_output_0_0 ;
    wire \adder_$add~17^ADD~0-2[1]_output_1_0 ;
    wire \adder_$add~15^ADD~1-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~13^ADD~2-2[1]_output_1_0 ;
    wire \adder_$add~15^ADD~1-1[1]_output_1_0 ;
    wire \adder_$add~15^ADD~1-1[1]_output_0_0 ;
    wire \adder_$add~13^ADD~2-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~11^ADD~3-2[1]_output_1_0 ;
    wire \adder_$add~13^ADD~2-1[1]_output_1_0 ;
    wire \adder_$add~13^ADD~2-1[1]_output_0_0 ;
    wire \adder_$add~11^ADD~3-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~9^ADD~4-2[1]_output_1_0 ;
    wire \adder_$add~11^ADD~3-1[1]_output_1_0 ;
    wire \adder_$add~11^ADD~3-1[1]_output_0_0 ;
    wire \adder_$add~9^ADD~4-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~7^ADD~5-2[1]_output_1_0 ;
    wire \adder_$add~9^ADD~4-1[1]_output_1_0 ;
    wire \adder_$add~9^ADD~4-1[1]_output_0_0 ;
    wire \adder_$add~7^ADD~5-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~5^ADD~6-2[1]_output_1_0 ;
    wire \adder_$add~7^ADD~5-1[1]_output_1_0 ;
    wire \adder_$add~7^ADD~5-1[1]_output_0_0 ;
    wire \adder_$add~5^ADD~6-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~3^ADD~7-2[1]_output_1_0 ;
    wire \adder_$add~5^ADD~6-1[1]_output_1_0 ;
    wire \adder_$add~5^ADD~6-1[1]_output_0_0 ;
    wire \adder_$add~3^ADD~7-0~dummy_output~0~1_output_0_0 ;
    wire \adder_$add~3^ADD~7-1[1]_output_1_0 ;
    wire \adder_$add~3^ADD~7-1[1]_output_0_0 ;
    wire \adder_$add~2^ADD~8-1[1]_input_0_0 ;
    wire \lut_n145_1_input_0_0 ;
    wire \lut_n149_1_input_0_3 ;
    wire \lut_n153_1_input_0_0 ;
    wire \lut_n157_1_input_0_3 ;
    wire \lut_n161_1_input_0_0 ;
    wire \lut_n165_1_input_0_3 ;
    wire \lut_n169_1_input_0_0 ;
    wire \lut_n173_1_input_0_3 ;
    wire \lut_n177_1_input_0_0 ;
    wire \latch_cout_clock_0_0 ;
    wire \latch_sum~0_clock_0_0 ;
    wire \latch_sum~1_clock_0_0 ;
    wire \latch_sum~2_clock_0_0 ;
    wire \latch_sum~3_clock_0_0 ;
    wire \latch_sum~4_clock_0_0 ;
    wire \latch_sum~5_clock_0_0 ;
    wire \latch_sum~6_clock_0_0 ;
    wire \latch_sum~7_clock_0_0 ;
    wire \adder_$add~14^ADD~14-1[1]_input_1_0 ;
    wire \adder_$add~4^ADD~9-1[1]_input_1_0 ;
    wire \adder_$add~6^ADD~10-1[1]_input_0_0 ;
    wire \adder_$add~10^ADD~12-1[1]_input_1_0 ;
    wire \adder_$add~8^ADD~11-1[1]_input_1_0 ;
    wire \adder_$add~14^ADD~14-1[1]_input_0_0 ;
    wire \adder_$add~6^ADD~10-1[1]_input_1_0 ;
    wire \adder_$add~12^ADD~13-1[1]_input_0_0 ;
    wire \adder_$add~3^ADD~7-1[1]_input_1_0 ;
    wire \adder_$add~10^ADD~12-1[1]_input_0_0 ;
    wire \adder_$add~16^ADD~15-1[1]_input_1_0 ;
    wire \adder_$add~16^ADD~15-1[1]_input_0_0 ;
    wire \adder_$add~4^ADD~9-1[1]_input_0_0 ;
    wire \adder_$add~8^ADD~11-1[1]_input_0_0 ;
    wire \adder_$add~2^ADD~8-1[1]_input_1_0 ;
    wire \adder_$add~12^ADD~13-1[1]_input_1_0 ;
    wire \sum~7_input_0_0 ;
    wire \sum~2_input_0_0 ;
    wire \cout_input_0_0 ;
    wire \sum~3_input_0_0 ;
    wire \sum~5_input_0_0 ;
    wire \sum~4_input_0_0 ;
    wire \sum~0_input_0_0 ;
    wire \sum~1_input_0_0 ;
    wire \sum~6_input_0_0 ;
    wire \latch_cout_input_0_0 ;
    wire \latch_sum~0_input_0_0 ;
    wire \latch_sum~1_input_0_0 ;
    wire \latch_sum~2_input_0_0 ;
    wire \latch_sum~3_input_0_0 ;
    wire \latch_sum~4_input_0_0 ;
    wire \latch_sum~5_input_0_0 ;
    wire \latch_sum~6_input_0_0 ;
    wire \latch_sum~7_input_0_0 ;
    wire \adder_$add~2^ADD~8-1[1]_input_2_0 ;
    wire \adder_$add~3^ADD~7-1[1]_input_0_0 ;
    wire \adder_$add~2^ADD~8-2[1]_input_2_0 ;
    wire \adder_$add~2^ADD~8-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~2^ADD~8-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~2^ADD~8-2[1]_input_0_0 ;
    wire \adder_$add~2^ADD~8-2[1]_input_1_0 ;
    wire \adder_$add~4^ADD~9-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~4^ADD~9-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~4^ADD~9-2[1]_input_0_0 ;
    wire \adder_$add~4^ADD~9-2[1]_input_1_0 ;
    wire \adder_$add~6^ADD~10-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~6^ADD~10-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~6^ADD~10-2[1]_input_0_0 ;
    wire \adder_$add~6^ADD~10-2[1]_input_1_0 ;
    wire \adder_$add~17^ADD~0-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~17^ADD~0-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~15^ADD~1-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~15^ADD~1-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~13^ADD~2-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~13^ADD~2-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~11^ADD~3-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~11^ADD~3-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~9^ADD~4-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~9^ADD~4-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~7^ADD~5-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~7^ADD~5-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~5^ADD~6-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~5^ADD~6-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~3^ADD~7-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~3^ADD~7-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~8^ADD~11-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~8^ADD~11-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~8^ADD~11-2[1]_input_0_0 ;
    wire \adder_$add~8^ADD~11-2[1]_input_1_0 ;
    wire \adder_$add~10^ADD~12-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~10^ADD~12-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~10^ADD~12-2[1]_input_0_0 ;
    wire \adder_$add~10^ADD~12-2[1]_input_1_0 ;
    wire \adder_$add~12^ADD~13-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~12^ADD~13-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~12^ADD~13-2[1]_input_0_0 ;
    wire \adder_$add~12^ADD~13-2[1]_input_1_0 ;
    wire \adder_$add~14^ADD~14-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~14^ADD~14-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~14^ADD~14-2[1]_input_0_0 ;
    wire \adder_$add~14^ADD~14-2[1]_input_1_0 ;
    wire \adder_$add~16^ADD~15-0~dummy_output~0~1_input_1_0 ;
    wire \adder_$add~16^ADD~15-0~dummy_output~0~1_input_2_0 ;
    wire \adder_$add~16^ADD~15-2[1]_input_0_0 ;
    wire \adder_$add~16^ADD~15-2[1]_input_1_0 ;
    wire \adder_$add~3^ADD~7-2[1]_input_0_0 ;
    wire \adder_$add~2^ADD~8-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~4^ADD~9-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~6^ADD~10-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~17^ADD~0-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~15^ADD~1-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~13^ADD~2-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~11^ADD~3-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~9^ADD~4-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~7^ADD~5-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~5^ADD~6-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~3^ADD~7-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~8^ADD~11-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~10^ADD~12-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~12^ADD~13-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~14^ADD~14-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~16^ADD~15-0~dummy_output~0~1_input_0_0 ;
    wire \adder_$add~4^ADD~9-1[1]_input_2_0 ;
    wire \adder_$add~5^ADD~6-1[1]_input_0_0 ;
    wire \adder_$add~4^ADD~9-2[1]_input_2_0 ;
    wire \adder_$add~5^ADD~6-2[1]_input_0_0 ;
    wire \adder_$add~6^ADD~10-1[1]_input_2_0 ;
    wire \adder_$add~7^ADD~5-1[1]_input_0_0 ;
    wire \adder_$add~6^ADD~10-2[1]_input_2_0 ;
    wire \adder_$add~7^ADD~5-2[1]_input_0_0 ;
    wire \adder_$add~8^ADD~11-1[1]_input_2_0 ;
    wire \adder_$add~9^ADD~4-1[1]_input_0_0 ;
    wire \adder_$add~8^ADD~11-2[1]_input_2_0 ;
    wire \adder_$add~9^ADD~4-2[1]_input_0_0 ;
    wire \adder_$add~10^ADD~12-1[1]_input_2_0 ;
    wire \adder_$add~11^ADD~3-1[1]_input_0_0 ;
    wire \adder_$add~10^ADD~12-2[1]_input_2_0 ;
    wire \adder_$add~11^ADD~3-2[1]_input_0_0 ;
    wire \adder_$add~12^ADD~13-1[1]_input_2_0 ;
    wire \adder_$add~13^ADD~2-1[1]_input_0_0 ;
    wire \adder_$add~12^ADD~13-2[1]_input_2_0 ;
    wire \adder_$add~13^ADD~2-2[1]_input_0_0 ;
    wire \adder_$add~14^ADD~14-1[1]_input_2_0 ;
    wire \adder_$add~15^ADD~1-1[1]_input_0_0 ;
    wire \adder_$add~14^ADD~14-2[1]_input_2_0 ;
    wire \adder_$add~15^ADD~1-2[1]_input_0_0 ;
    wire \adder_$add~16^ADD~15-1[1]_input_2_0 ;
    wire \adder_$add~17^ADD~0-1[1]_input_0_0 ;
    wire \adder_$add~16^ADD~15-2[1]_input_2_0 ;
    wire \adder_$add~17^ADD~0-2[1]_input_0_0 ;
    wire \adder_$add~17^ADD~0-1[1]_input_2_0 ;
    wire \adder_$add~17^ADD~0-1[1]_input_1_0 ;
    wire \lut_n177_1_input_0_2 ;
    wire \adder_$add~17^ADD~0-2[1]_input_2_0 ;
    wire \lut_n145_1_input_0_3 ;
    wire \adder_$add~15^ADD~1-1[1]_input_2_0 ;
    wire \adder_$add~15^ADD~1-1[1]_input_1_0 ;
    wire \lut_n173_1_input_0_1 ;
    wire \adder_$add~15^ADD~1-2[1]_input_2_0 ;
    wire \adder_$add~13^ADD~2-1[1]_input_2_0 ;
    wire \adder_$add~13^ADD~2-1[1]_input_1_0 ;
    wire \lut_n169_1_input_0_3 ;
    wire \adder_$add~13^ADD~2-2[1]_input_2_0 ;
    wire \adder_$add~11^ADD~3-1[1]_input_2_0 ;
    wire \adder_$add~11^ADD~3-1[1]_input_1_0 ;
    wire \lut_n165_1_input_0_2 ;
    wire \adder_$add~11^ADD~3-2[1]_input_2_0 ;
    wire \adder_$add~9^ADD~4-1[1]_input_2_0 ;
    wire \adder_$add~9^ADD~4-1[1]_input_1_0 ;
    wire \lut_n161_1_input_0_3 ;
    wire \adder_$add~9^ADD~4-2[1]_input_2_0 ;
    wire \adder_$add~7^ADD~5-1[1]_input_2_0 ;
    wire \adder_$add~7^ADD~5-1[1]_input_1_0 ;
    wire \lut_n157_1_input_0_2 ;
    wire \adder_$add~7^ADD~5-2[1]_input_2_0 ;
    wire \adder_$add~5^ADD~6-1[1]_input_2_0 ;
    wire \adder_$add~5^ADD~6-1[1]_input_1_0 ;
    wire \lut_n153_1_input_0_4 ;
    wire \adder_$add~5^ADD~6-2[1]_input_2_0 ;
    wire \adder_$add~3^ADD~7-1[1]_input_2_0 ;
    wire \lut_n149_1_input_0_2 ;
    wire \adder_$add~3^ADD~7-2[1]_input_2_0 ;

    //IO assignments
    assign \sum~7  = \sum~7_input_0_0 ;
    assign \sum~2  = \sum~2_input_0_0 ;
    assign \cout  = \cout_input_0_0 ;
    assign \sum~3  = \sum~3_input_0_0 ;
    assign \sum~5  = \sum~5_input_0_0 ;
    assign \sum~4  = \sum~4_input_0_0 ;
    assign \sum~0  = \sum~0_input_0_0 ;
    assign \sum~1  = \sum~1_input_0_0 ;
    assign \sum~6  = \sum~6_input_0_0 ;
    assign \a~0_output_0_0  = \a~0 ;
    assign \rst_output_0_0  = \rst ;
    assign \clk_output_0_0  = \clk ;
    assign \b~6_output_0_0  = \b~6 ;
    assign \b~1_output_0_0  = \b~1 ;
    assign \a~2_output_0_0  = \a~2 ;
    assign \b~4_output_0_0  = \b~4 ;
    assign \b~3_output_0_0  = \b~3 ;
    assign \a~6_output_0_0  = \a~6 ;
    assign \b~2_output_0_0  = \b~2 ;
    assign \a~5_output_0_0  = \a~5 ;
    assign \cin_output_0_0  = \cin ;
    assign \a~4_output_0_0  = \a~4 ;
    assign \b~7_output_0_0  = \b~7 ;
    assign \a~7_output_0_0  = \a~7 ;
    assign \a~1_output_0_0  = \a~1 ;
    assign \a~3_output_0_0  = \a~3 ;
    assign \b~0_output_0_0  = \b~0 ;
    assign \b~5_output_0_0  = \b~5 ;

    //Interconnect
    fpga_interconnect \routing_segment_a~0_output_0_0_to_adder_$add~2^ADD~8-1[1]_input_0_0  (
        .datain(\a~0_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n145_1_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n145_1_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n149_1_input_0_3  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n149_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n153_1_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n153_1_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n157_1_input_0_3  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n157_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n161_1_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n161_1_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n165_1_input_0_3  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n165_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n169_1_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n169_1_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n173_1_input_0_3  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n173_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n177_1_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n177_1_input_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_cout_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_cout_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~0_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~0_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~1_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~1_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~2_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~2_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~3_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~3_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~4_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~4_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~5_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~5_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~6_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~6_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_sum~7_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_sum~7_clock_0_0 )
    );

    fpga_interconnect \routing_segment_b~6_output_0_0_to_adder_$add~14^ADD~14-1[1]_input_1_0  (
        .datain(\b~6_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_b~1_output_0_0_to_adder_$add~4^ADD~9-1[1]_input_1_0  (
        .datain(\b~1_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_a~2_output_0_0_to_adder_$add~6^ADD~10-1[1]_input_0_0  (
        .datain(\a~2_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_b~4_output_0_0_to_adder_$add~10^ADD~12-1[1]_input_1_0  (
        .datain(\b~4_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_b~3_output_0_0_to_adder_$add~8^ADD~11-1[1]_input_1_0  (
        .datain(\b~3_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_a~6_output_0_0_to_adder_$add~14^ADD~14-1[1]_input_0_0  (
        .datain(\a~6_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_b~2_output_0_0_to_adder_$add~6^ADD~10-1[1]_input_1_0  (
        .datain(\b~2_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_a~5_output_0_0_to_adder_$add~12^ADD~13-1[1]_input_0_0  (
        .datain(\a~5_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_cin_output_0_0_to_adder_$add~3^ADD~7-1[1]_input_1_0  (
        .datain(\cin_output_0_0 ),
        .dataout(\adder_$add~3^ADD~7-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_a~4_output_0_0_to_adder_$add~10^ADD~12-1[1]_input_0_0  (
        .datain(\a~4_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_b~7_output_0_0_to_adder_$add~16^ADD~15-1[1]_input_1_0  (
        .datain(\b~7_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_a~7_output_0_0_to_adder_$add~16^ADD~15-1[1]_input_0_0  (
        .datain(\a~7_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_a~1_output_0_0_to_adder_$add~4^ADD~9-1[1]_input_0_0  (
        .datain(\a~1_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_a~3_output_0_0_to_adder_$add~8^ADD~11-1[1]_input_0_0  (
        .datain(\a~3_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_b~0_output_0_0_to_adder_$add~2^ADD~8-1[1]_input_1_0  (
        .datain(\b~0_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_b~5_output_0_0_to_adder_$add~12^ADD~13-1[1]_input_1_0  (
        .datain(\b~5_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~7_output_0_0_to_sum~7_input_0_0  (
        .datain(\latch_sum~7_output_0_0 ),
        .dataout(\sum~7_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~2_output_0_0_to_sum~2_input_0_0  (
        .datain(\latch_sum~2_output_0_0 ),
        .dataout(\sum~2_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_cout_output_0_0_to_cout_input_0_0  (
        .datain(\latch_cout_output_0_0 ),
        .dataout(\cout_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~3_output_0_0_to_sum~3_input_0_0  (
        .datain(\latch_sum~3_output_0_0 ),
        .dataout(\sum~3_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~5_output_0_0_to_sum~5_input_0_0  (
        .datain(\latch_sum~5_output_0_0 ),
        .dataout(\sum~5_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~4_output_0_0_to_sum~4_input_0_0  (
        .datain(\latch_sum~4_output_0_0 ),
        .dataout(\sum~4_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~0_output_0_0_to_sum~0_input_0_0  (
        .datain(\latch_sum~0_output_0_0 ),
        .dataout(\sum~0_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~1_output_0_0_to_sum~1_input_0_0  (
        .datain(\latch_sum~1_output_0_0 ),
        .dataout(\sum~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_sum~6_output_0_0_to_sum~6_input_0_0  (
        .datain(\latch_sum~6_output_0_0 ),
        .dataout(\sum~6_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n145_1_output_0_0_to_latch_cout_input_0_0  (
        .datain(\lut_n145_1_output_0_0 ),
        .dataout(\latch_cout_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n149_1_output_0_0_to_latch_sum~0_input_0_0  (
        .datain(\lut_n149_1_output_0_0 ),
        .dataout(\latch_sum~0_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n153_1_output_0_0_to_latch_sum~1_input_0_0  (
        .datain(\lut_n153_1_output_0_0 ),
        .dataout(\latch_sum~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n157_1_output_0_0_to_latch_sum~2_input_0_0  (
        .datain(\lut_n157_1_output_0_0 ),
        .dataout(\latch_sum~2_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n161_1_output_0_0_to_latch_sum~3_input_0_0  (
        .datain(\lut_n161_1_output_0_0 ),
        .dataout(\latch_sum~3_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n165_1_output_0_0_to_latch_sum~4_input_0_0  (
        .datain(\lut_n165_1_output_0_0 ),
        .dataout(\latch_sum~4_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n169_1_output_0_0_to_latch_sum~5_input_0_0  (
        .datain(\lut_n169_1_output_0_0 ),
        .dataout(\latch_sum~5_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n173_1_output_0_0_to_latch_sum~6_input_0_0  (
        .datain(\lut_n173_1_output_0_0 ),
        .dataout(\latch_sum~6_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n177_1_output_0_0_to_latch_sum~7_input_0_0  (
        .datain(\lut_n177_1_output_0_0 ),
        .dataout(\latch_sum~7_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~2^ADD~8-0~dummy_output~0~1_output_0_0_to_adder_$add~2^ADD~8-1[1]_input_2_0  (
        .datain(\adder_$add~2^ADD~8-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~2^ADD~8-1[1]_output_1_0_to_adder_$add~3^ADD~7-1[1]_input_0_0  (
        .datain(\adder_$add~2^ADD~8-1[1]_output_1_0 ),
        .dataout(\adder_$add~3^ADD~7-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~2^ADD~8-1[1]_output_0_0_to_adder_$add~2^ADD~8-2[1]_input_2_0  (
        .datain(\adder_$add~2^ADD~8-1[1]_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~2^ADD~8-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~2^ADD~8-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~2^ADD~8-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~2^ADD~8-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~4^ADD~9-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~4^ADD~9-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~4^ADD~9-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~4^ADD~9-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~6^ADD~10-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~6^ADD~10-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~6^ADD~10-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~6^ADD~10-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~17^ADD~0-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~17^ADD~0-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~17^ADD~0-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~17^ADD~0-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~15^ADD~1-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~15^ADD~1-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~15^ADD~1-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~15^ADD~1-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~13^ADD~2-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~13^ADD~2-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~13^ADD~2-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~13^ADD~2-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~11^ADD~3-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~11^ADD~3-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~11^ADD~3-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~11^ADD~3-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~9^ADD~4-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~9^ADD~4-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~9^ADD~4-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~9^ADD~4-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~7^ADD~5-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~7^ADD~5-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~7^ADD~5-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~7^ADD~5-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~5^ADD~6-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~5^ADD~6-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~5^ADD~6-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~5^ADD~6-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~3^ADD~7-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~3^ADD~7-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~3^ADD~7-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~3^ADD~7-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~8^ADD~11-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~8^ADD~11-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~8^ADD~11-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~8^ADD~11-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~10^ADD~12-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~10^ADD~12-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~10^ADD~12-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~10^ADD~12-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~12^ADD~13-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~12^ADD~13-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~12^ADD~13-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~12^ADD~13-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~14^ADD~14-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~14^ADD~14-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~14^ADD~14-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~14^ADD~14-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~16^ADD~15-0~dummy_output~0~1_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-0~dummy_output~0~1_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~16^ADD~15-0~dummy_output~0~1_input_2_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-0~dummy_output~0~1_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~16^ADD~15-2[1]_input_0_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_gnd_output_0_0_to_adder_$add~16^ADD~15-2[1]_input_1_0  (
        .datain(\lut_gnd_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-2[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~2^ADD~8-2[1]_output_1_0_to_adder_$add~3^ADD~7-2[1]_input_0_0  (
        .datain(\adder_$add~2^ADD~8-2[1]_output_1_0 ),
        .dataout(\adder_$add~3^ADD~7-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~2^ADD~8-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~2^ADD~8-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~4^ADD~9-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~6^ADD~10-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~17^ADD~0-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~17^ADD~0-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~15^ADD~1-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~15^ADD~1-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~13^ADD~2-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~13^ADD~2-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~11^ADD~3-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~11^ADD~3-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~9^ADD~4-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~9^ADD~4-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~7^ADD~5-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~7^ADD~5-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~5^ADD~6-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~5^ADD~6-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~3^ADD~7-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~3^ADD~7-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~8^ADD~11-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~10^ADD~12-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~12^ADD~13-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~14^ADD~14-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_vcc_output_0_0_to_adder_$add~16^ADD~15-0~dummy_output~0~1_input_0_0  (
        .datain(\lut_vcc_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-0~dummy_output~0~1_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~4^ADD~9-0~dummy_output~0~1_output_0_0_to_adder_$add~4^ADD~9-1[1]_input_2_0  (
        .datain(\adder_$add~4^ADD~9-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~4^ADD~9-1[1]_output_1_0_to_adder_$add~5^ADD~6-1[1]_input_0_0  (
        .datain(\adder_$add~4^ADD~9-1[1]_output_1_0 ),
        .dataout(\adder_$add~5^ADD~6-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~4^ADD~9-1[1]_output_0_0_to_adder_$add~4^ADD~9-2[1]_input_2_0  (
        .datain(\adder_$add~4^ADD~9-1[1]_output_0_0 ),
        .dataout(\adder_$add~4^ADD~9-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~4^ADD~9-2[1]_output_1_0_to_adder_$add~5^ADD~6-2[1]_input_0_0  (
        .datain(\adder_$add~4^ADD~9-2[1]_output_1_0 ),
        .dataout(\adder_$add~5^ADD~6-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~6^ADD~10-0~dummy_output~0~1_output_0_0_to_adder_$add~6^ADD~10-1[1]_input_2_0  (
        .datain(\adder_$add~6^ADD~10-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~6^ADD~10-1[1]_output_1_0_to_adder_$add~7^ADD~5-1[1]_input_0_0  (
        .datain(\adder_$add~6^ADD~10-1[1]_output_1_0 ),
        .dataout(\adder_$add~7^ADD~5-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~6^ADD~10-1[1]_output_0_0_to_adder_$add~6^ADD~10-2[1]_input_2_0  (
        .datain(\adder_$add~6^ADD~10-1[1]_output_0_0 ),
        .dataout(\adder_$add~6^ADD~10-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~6^ADD~10-2[1]_output_1_0_to_adder_$add~7^ADD~5-2[1]_input_0_0  (
        .datain(\adder_$add~6^ADD~10-2[1]_output_1_0 ),
        .dataout(\adder_$add~7^ADD~5-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~8^ADD~11-0~dummy_output~0~1_output_0_0_to_adder_$add~8^ADD~11-1[1]_input_2_0  (
        .datain(\adder_$add~8^ADD~11-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~8^ADD~11-1[1]_output_1_0_to_adder_$add~9^ADD~4-1[1]_input_0_0  (
        .datain(\adder_$add~8^ADD~11-1[1]_output_1_0 ),
        .dataout(\adder_$add~9^ADD~4-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~8^ADD~11-1[1]_output_0_0_to_adder_$add~8^ADD~11-2[1]_input_2_0  (
        .datain(\adder_$add~8^ADD~11-1[1]_output_0_0 ),
        .dataout(\adder_$add~8^ADD~11-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~8^ADD~11-2[1]_output_1_0_to_adder_$add~9^ADD~4-2[1]_input_0_0  (
        .datain(\adder_$add~8^ADD~11-2[1]_output_1_0 ),
        .dataout(\adder_$add~9^ADD~4-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~10^ADD~12-0~dummy_output~0~1_output_0_0_to_adder_$add~10^ADD~12-1[1]_input_2_0  (
        .datain(\adder_$add~10^ADD~12-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~10^ADD~12-1[1]_output_1_0_to_adder_$add~11^ADD~3-1[1]_input_0_0  (
        .datain(\adder_$add~10^ADD~12-1[1]_output_1_0 ),
        .dataout(\adder_$add~11^ADD~3-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~10^ADD~12-1[1]_output_0_0_to_adder_$add~10^ADD~12-2[1]_input_2_0  (
        .datain(\adder_$add~10^ADD~12-1[1]_output_0_0 ),
        .dataout(\adder_$add~10^ADD~12-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~10^ADD~12-2[1]_output_1_0_to_adder_$add~11^ADD~3-2[1]_input_0_0  (
        .datain(\adder_$add~10^ADD~12-2[1]_output_1_0 ),
        .dataout(\adder_$add~11^ADD~3-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~12^ADD~13-0~dummy_output~0~1_output_0_0_to_adder_$add~12^ADD~13-1[1]_input_2_0  (
        .datain(\adder_$add~12^ADD~13-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~12^ADD~13-1[1]_output_1_0_to_adder_$add~13^ADD~2-1[1]_input_0_0  (
        .datain(\adder_$add~12^ADD~13-1[1]_output_1_0 ),
        .dataout(\adder_$add~13^ADD~2-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~12^ADD~13-1[1]_output_0_0_to_adder_$add~12^ADD~13-2[1]_input_2_0  (
        .datain(\adder_$add~12^ADD~13-1[1]_output_0_0 ),
        .dataout(\adder_$add~12^ADD~13-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~12^ADD~13-2[1]_output_1_0_to_adder_$add~13^ADD~2-2[1]_input_0_0  (
        .datain(\adder_$add~12^ADD~13-2[1]_output_1_0 ),
        .dataout(\adder_$add~13^ADD~2-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~14^ADD~14-0~dummy_output~0~1_output_0_0_to_adder_$add~14^ADD~14-1[1]_input_2_0  (
        .datain(\adder_$add~14^ADD~14-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~14^ADD~14-1[1]_output_1_0_to_adder_$add~15^ADD~1-1[1]_input_0_0  (
        .datain(\adder_$add~14^ADD~14-1[1]_output_1_0 ),
        .dataout(\adder_$add~15^ADD~1-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~14^ADD~14-1[1]_output_0_0_to_adder_$add~14^ADD~14-2[1]_input_2_0  (
        .datain(\adder_$add~14^ADD~14-1[1]_output_0_0 ),
        .dataout(\adder_$add~14^ADD~14-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~14^ADD~14-2[1]_output_1_0_to_adder_$add~15^ADD~1-2[1]_input_0_0  (
        .datain(\adder_$add~14^ADD~14-2[1]_output_1_0 ),
        .dataout(\adder_$add~15^ADD~1-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~16^ADD~15-0~dummy_output~0~1_output_0_0_to_adder_$add~16^ADD~15-1[1]_input_2_0  (
        .datain(\adder_$add~16^ADD~15-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~16^ADD~15-1[1]_output_1_0_to_adder_$add~17^ADD~0-1[1]_input_0_0  (
        .datain(\adder_$add~16^ADD~15-1[1]_output_1_0 ),
        .dataout(\adder_$add~17^ADD~0-1[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~16^ADD~15-1[1]_output_0_0_to_adder_$add~16^ADD~15-2[1]_input_2_0  (
        .datain(\adder_$add~16^ADD~15-1[1]_output_0_0 ),
        .dataout(\adder_$add~16^ADD~15-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~16^ADD~15-2[1]_output_1_0_to_adder_$add~17^ADD~0-2[1]_input_0_0  (
        .datain(\adder_$add~16^ADD~15-2[1]_output_1_0 ),
        .dataout(\adder_$add~17^ADD~0-2[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~17^ADD~0-0~dummy_output~0~1_output_0_0_to_adder_$add~17^ADD~0-1[1]_input_2_0  (
        .datain(\adder_$add~17^ADD~0-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~17^ADD~0-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~15^ADD~1-2[1]_output_1_0_to_adder_$add~17^ADD~0-1[1]_input_1_0  (
        .datain(\adder_$add~15^ADD~1-2[1]_output_1_0 ),
        .dataout(\adder_$add~17^ADD~0-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~17^ADD~0-1[1]_output_1_0_to_lut_n177_1_input_0_2  (
        .datain(\adder_$add~17^ADD~0-1[1]_output_1_0 ),
        .dataout(\lut_n177_1_input_0_2 )
    );

    fpga_interconnect \routing_segment_adder_$add~17^ADD~0-1[1]_output_0_0_to_adder_$add~17^ADD~0-2[1]_input_2_0  (
        .datain(\adder_$add~17^ADD~0-1[1]_output_0_0 ),
        .dataout(\adder_$add~17^ADD~0-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~17^ADD~0-2[1]_output_1_0_to_lut_n145_1_input_0_3  (
        .datain(\adder_$add~17^ADD~0-2[1]_output_1_0 ),
        .dataout(\lut_n145_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_adder_$add~15^ADD~1-0~dummy_output~0~1_output_0_0_to_adder_$add~15^ADD~1-1[1]_input_2_0  (
        .datain(\adder_$add~15^ADD~1-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~15^ADD~1-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~13^ADD~2-2[1]_output_1_0_to_adder_$add~15^ADD~1-1[1]_input_1_0  (
        .datain(\adder_$add~13^ADD~2-2[1]_output_1_0 ),
        .dataout(\adder_$add~15^ADD~1-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~15^ADD~1-1[1]_output_1_0_to_lut_n173_1_input_0_1  (
        .datain(\adder_$add~15^ADD~1-1[1]_output_1_0 ),
        .dataout(\lut_n173_1_input_0_1 )
    );

    fpga_interconnect \routing_segment_adder_$add~15^ADD~1-1[1]_output_0_0_to_adder_$add~15^ADD~1-2[1]_input_2_0  (
        .datain(\adder_$add~15^ADD~1-1[1]_output_0_0 ),
        .dataout(\adder_$add~15^ADD~1-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~13^ADD~2-0~dummy_output~0~1_output_0_0_to_adder_$add~13^ADD~2-1[1]_input_2_0  (
        .datain(\adder_$add~13^ADD~2-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~13^ADD~2-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~11^ADD~3-2[1]_output_1_0_to_adder_$add~13^ADD~2-1[1]_input_1_0  (
        .datain(\adder_$add~11^ADD~3-2[1]_output_1_0 ),
        .dataout(\adder_$add~13^ADD~2-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~13^ADD~2-1[1]_output_1_0_to_lut_n169_1_input_0_3  (
        .datain(\adder_$add~13^ADD~2-1[1]_output_1_0 ),
        .dataout(\lut_n169_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_adder_$add~13^ADD~2-1[1]_output_0_0_to_adder_$add~13^ADD~2-2[1]_input_2_0  (
        .datain(\adder_$add~13^ADD~2-1[1]_output_0_0 ),
        .dataout(\adder_$add~13^ADD~2-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~11^ADD~3-0~dummy_output~0~1_output_0_0_to_adder_$add~11^ADD~3-1[1]_input_2_0  (
        .datain(\adder_$add~11^ADD~3-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~11^ADD~3-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~9^ADD~4-2[1]_output_1_0_to_adder_$add~11^ADD~3-1[1]_input_1_0  (
        .datain(\adder_$add~9^ADD~4-2[1]_output_1_0 ),
        .dataout(\adder_$add~11^ADD~3-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~11^ADD~3-1[1]_output_1_0_to_lut_n165_1_input_0_2  (
        .datain(\adder_$add~11^ADD~3-1[1]_output_1_0 ),
        .dataout(\lut_n165_1_input_0_2 )
    );

    fpga_interconnect \routing_segment_adder_$add~11^ADD~3-1[1]_output_0_0_to_adder_$add~11^ADD~3-2[1]_input_2_0  (
        .datain(\adder_$add~11^ADD~3-1[1]_output_0_0 ),
        .dataout(\adder_$add~11^ADD~3-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~9^ADD~4-0~dummy_output~0~1_output_0_0_to_adder_$add~9^ADD~4-1[1]_input_2_0  (
        .datain(\adder_$add~9^ADD~4-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~9^ADD~4-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~7^ADD~5-2[1]_output_1_0_to_adder_$add~9^ADD~4-1[1]_input_1_0  (
        .datain(\adder_$add~7^ADD~5-2[1]_output_1_0 ),
        .dataout(\adder_$add~9^ADD~4-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~9^ADD~4-1[1]_output_1_0_to_lut_n161_1_input_0_3  (
        .datain(\adder_$add~9^ADD~4-1[1]_output_1_0 ),
        .dataout(\lut_n161_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_adder_$add~9^ADD~4-1[1]_output_0_0_to_adder_$add~9^ADD~4-2[1]_input_2_0  (
        .datain(\adder_$add~9^ADD~4-1[1]_output_0_0 ),
        .dataout(\adder_$add~9^ADD~4-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~7^ADD~5-0~dummy_output~0~1_output_0_0_to_adder_$add~7^ADD~5-1[1]_input_2_0  (
        .datain(\adder_$add~7^ADD~5-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~7^ADD~5-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~5^ADD~6-2[1]_output_1_0_to_adder_$add~7^ADD~5-1[1]_input_1_0  (
        .datain(\adder_$add~5^ADD~6-2[1]_output_1_0 ),
        .dataout(\adder_$add~7^ADD~5-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~7^ADD~5-1[1]_output_1_0_to_lut_n157_1_input_0_2  (
        .datain(\adder_$add~7^ADD~5-1[1]_output_1_0 ),
        .dataout(\lut_n157_1_input_0_2 )
    );

    fpga_interconnect \routing_segment_adder_$add~7^ADD~5-1[1]_output_0_0_to_adder_$add~7^ADD~5-2[1]_input_2_0  (
        .datain(\adder_$add~7^ADD~5-1[1]_output_0_0 ),
        .dataout(\adder_$add~7^ADD~5-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~5^ADD~6-0~dummy_output~0~1_output_0_0_to_adder_$add~5^ADD~6-1[1]_input_2_0  (
        .datain(\adder_$add~5^ADD~6-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~5^ADD~6-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~3^ADD~7-2[1]_output_1_0_to_adder_$add~5^ADD~6-1[1]_input_1_0  (
        .datain(\adder_$add~3^ADD~7-2[1]_output_1_0 ),
        .dataout(\adder_$add~5^ADD~6-1[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~5^ADD~6-1[1]_output_1_0_to_lut_n153_1_input_0_4  (
        .datain(\adder_$add~5^ADD~6-1[1]_output_1_0 ),
        .dataout(\lut_n153_1_input_0_4 )
    );

    fpga_interconnect \routing_segment_adder_$add~5^ADD~6-1[1]_output_0_0_to_adder_$add~5^ADD~6-2[1]_input_2_0  (
        .datain(\adder_$add~5^ADD~6-1[1]_output_0_0 ),
        .dataout(\adder_$add~5^ADD~6-2[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~3^ADD~7-0~dummy_output~0~1_output_0_0_to_adder_$add~3^ADD~7-1[1]_input_2_0  (
        .datain(\adder_$add~3^ADD~7-0~dummy_output~0~1_output_0_0 ),
        .dataout(\adder_$add~3^ADD~7-1[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_adder_$add~3^ADD~7-1[1]_output_1_0_to_lut_n149_1_input_0_2  (
        .datain(\adder_$add~3^ADD~7-1[1]_output_1_0 ),
        .dataout(\lut_n149_1_input_0_2 )
    );

    fpga_interconnect \routing_segment_adder_$add~3^ADD~7-1[1]_output_0_0_to_adder_$add~3^ADD~7-2[1]_input_2_0  (
        .datain(\adder_$add~3^ADD~7-1[1]_output_0_0 ),
        .dataout(\adder_$add~3^ADD~7-2[1]_input_2_0 )
    );


    //Cell instances
    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~2^ADD~8-0~dummy_output~0~1  (
        .a(\adder_$add~2^ADD~8-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~2^ADD~8-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~2^ADD~8-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~2^ADD~8-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~2^ADD~8-1[1]  (
        .a(\adder_$add~2^ADD~8-1[1]_input_0_0 ),
        .b(\adder_$add~2^ADD~8-1[1]_input_1_0 ),
        .cin(\adder_$add~2^ADD~8-1[1]_input_2_0 ),
        .cout(\adder_$add~2^ADD~8-1[1]_output_0_0 ),
        .sumout(\adder_$add~2^ADD~8-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~2^ADD~8-2[1]  (
        .a(\adder_$add~2^ADD~8-2[1]_input_0_0 ),
        .b(\adder_$add~2^ADD~8-2[1]_input_1_0 ),
        .cin(\adder_$add~2^ADD~8-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~2^ADD~8-2[1]_output_1_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000001)
    ) \lut_vcc  (
        .in({
            1'bX,
            1'bX,
            1'bX,
            1'bX,
            1'bX
         }),
        .out(\lut_vcc_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b11111111111111111111111111111110)
    ) \lut_gnd  (
        .in({
            1'bX,
            1'bX,
            1'bX,
            1'bX,
            1'bX
         }),
        .out(\lut_gnd_output_0_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~4^ADD~9-0~dummy_output~0~1  (
        .a(\adder_$add~4^ADD~9-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~4^ADD~9-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~4^ADD~9-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~4^ADD~9-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~4^ADD~9-1[1]  (
        .a(\adder_$add~4^ADD~9-1[1]_input_0_0 ),
        .b(\adder_$add~4^ADD~9-1[1]_input_1_0 ),
        .cin(\adder_$add~4^ADD~9-1[1]_input_2_0 ),
        .cout(\adder_$add~4^ADD~9-1[1]_output_0_0 ),
        .sumout(\adder_$add~4^ADD~9-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~4^ADD~9-2[1]  (
        .a(\adder_$add~4^ADD~9-2[1]_input_0_0 ),
        .b(\adder_$add~4^ADD~9-2[1]_input_1_0 ),
        .cin(\adder_$add~4^ADD~9-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~4^ADD~9-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~6^ADD~10-0~dummy_output~0~1  (
        .a(\adder_$add~6^ADD~10-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~6^ADD~10-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~6^ADD~10-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~6^ADD~10-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~6^ADD~10-1[1]  (
        .a(\adder_$add~6^ADD~10-1[1]_input_0_0 ),
        .b(\adder_$add~6^ADD~10-1[1]_input_1_0 ),
        .cin(\adder_$add~6^ADD~10-1[1]_input_2_0 ),
        .cout(\adder_$add~6^ADD~10-1[1]_output_0_0 ),
        .sumout(\adder_$add~6^ADD~10-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~6^ADD~10-2[1]  (
        .a(\adder_$add~6^ADD~10-2[1]_input_0_0 ),
        .b(\adder_$add~6^ADD~10-2[1]_input_1_0 ),
        .cin(\adder_$add~6^ADD~10-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~6^ADD~10-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~17^ADD~0-0~dummy_output~0~1  (
        .a(\adder_$add~17^ADD~0-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~17^ADD~0-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~17^ADD~0-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~17^ADD~0-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~17^ADD~0-1[1]  (
        .a(\adder_$add~17^ADD~0-1[1]_input_0_0 ),
        .b(\adder_$add~17^ADD~0-1[1]_input_1_0 ),
        .cin(\adder_$add~17^ADD~0-1[1]_input_2_0 ),
        .cout(\adder_$add~17^ADD~0-1[1]_output_0_0 ),
        .sumout(\adder_$add~17^ADD~0-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~17^ADD~0-2[1]  (
        .a(\adder_$add~17^ADD~0-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~17^ADD~0-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~17^ADD~0-2[1]_output_1_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000100000000)
    ) \lut_n145_1  (
        .in({
            1'bX,
            \lut_n145_1_input_0_3 ,
            1'bX,
            1'bX,
            \lut_n145_1_input_0_0 
         }),
        .out(\lut_n145_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_cout  (
        .D(\latch_cout_input_0_0 ), 
        .Q(\latch_cout_output_0_0 ), 
        .clk(\latch_cout_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000010000)
    ) \lut_n149_1  (
        .in({
            1'bX,
            \lut_n149_1_input_0_3 ,
            \lut_n149_1_input_0_2 ,
            1'bX,
            1'bX
         }),
        .out(\lut_n149_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~0  (
        .D(\latch_sum~0_input_0_0 ), 
        .Q(\latch_sum~0_output_0_0 ), 
        .clk(\latch_sum~0_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000010000000000000000)
    ) \lut_n153_1  (
        .in({
            \lut_n153_1_input_0_4 ,
            1'bX,
            1'bX,
            1'bX,
            \lut_n153_1_input_0_0 
         }),
        .out(\lut_n153_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~1  (
        .D(\latch_sum~1_input_0_0 ), 
        .Q(\latch_sum~1_output_0_0 ), 
        .clk(\latch_sum~1_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000010000)
    ) \lut_n157_1  (
        .in({
            1'bX,
            \lut_n157_1_input_0_3 ,
            \lut_n157_1_input_0_2 ,
            1'bX,
            1'bX
         }),
        .out(\lut_n157_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~2  (
        .D(\latch_sum~2_input_0_0 ), 
        .Q(\latch_sum~2_output_0_0 ), 
        .clk(\latch_sum~2_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000100000000)
    ) \lut_n161_1  (
        .in({
            1'bX,
            \lut_n161_1_input_0_3 ,
            1'bX,
            1'bX,
            \lut_n161_1_input_0_0 
         }),
        .out(\lut_n161_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~3  (
        .D(\latch_sum~3_input_0_0 ), 
        .Q(\latch_sum~3_output_0_0 ), 
        .clk(\latch_sum~3_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000010000)
    ) \lut_n165_1  (
        .in({
            1'bX,
            \lut_n165_1_input_0_3 ,
            \lut_n165_1_input_0_2 ,
            1'bX,
            1'bX
         }),
        .out(\lut_n165_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~4  (
        .D(\latch_sum~4_input_0_0 ), 
        .Q(\latch_sum~4_output_0_0 ), 
        .clk(\latch_sum~4_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000100000000)
    ) \lut_n169_1  (
        .in({
            1'bX,
            \lut_n169_1_input_0_3 ,
            1'bX,
            1'bX,
            \lut_n169_1_input_0_0 
         }),
        .out(\lut_n169_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~5  (
        .D(\latch_sum~5_input_0_0 ), 
        .Q(\latch_sum~5_output_0_0 ), 
        .clk(\latch_sum~5_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000100)
    ) \lut_n173_1  (
        .in({
            1'bX,
            \lut_n173_1_input_0_3 ,
            1'bX,
            \lut_n173_1_input_0_1 ,
            1'bX
         }),
        .out(\lut_n173_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~6  (
        .D(\latch_sum~6_input_0_0 ), 
        .Q(\latch_sum~6_output_0_0 ), 
        .clk(\latch_sum~6_clock_0_0 )
    );
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000010000)
    ) \lut_n177_1  (
        .in({
            1'bX,
            1'bX,
            \lut_n177_1_input_0_2 ,
            1'bX,
            \lut_n177_1_input_0_0 
         }),
        .out(\lut_n177_1_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_sum~7  (
        .D(\latch_sum~7_input_0_0 ), 
        .Q(\latch_sum~7_output_0_0 ), 
        .clk(\latch_sum~7_clock_0_0 )
    );
    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~15^ADD~1-0~dummy_output~0~1  (
        .a(\adder_$add~15^ADD~1-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~15^ADD~1-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~15^ADD~1-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~15^ADD~1-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~15^ADD~1-1[1]  (
        .a(\adder_$add~15^ADD~1-1[1]_input_0_0 ),
        .b(\adder_$add~15^ADD~1-1[1]_input_1_0 ),
        .cin(\adder_$add~15^ADD~1-1[1]_input_2_0 ),
        .cout(\adder_$add~15^ADD~1-1[1]_output_0_0 ),
        .sumout(\adder_$add~15^ADD~1-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~15^ADD~1-2[1]  (
        .a(\adder_$add~15^ADD~1-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~15^ADD~1-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~15^ADD~1-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~13^ADD~2-0~dummy_output~0~1  (
        .a(\adder_$add~13^ADD~2-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~13^ADD~2-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~13^ADD~2-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~13^ADD~2-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~13^ADD~2-1[1]  (
        .a(\adder_$add~13^ADD~2-1[1]_input_0_0 ),
        .b(\adder_$add~13^ADD~2-1[1]_input_1_0 ),
        .cin(\adder_$add~13^ADD~2-1[1]_input_2_0 ),
        .cout(\adder_$add~13^ADD~2-1[1]_output_0_0 ),
        .sumout(\adder_$add~13^ADD~2-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~13^ADD~2-2[1]  (
        .a(\adder_$add~13^ADD~2-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~13^ADD~2-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~13^ADD~2-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~11^ADD~3-0~dummy_output~0~1  (
        .a(\adder_$add~11^ADD~3-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~11^ADD~3-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~11^ADD~3-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~11^ADD~3-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~11^ADD~3-1[1]  (
        .a(\adder_$add~11^ADD~3-1[1]_input_0_0 ),
        .b(\adder_$add~11^ADD~3-1[1]_input_1_0 ),
        .cin(\adder_$add~11^ADD~3-1[1]_input_2_0 ),
        .cout(\adder_$add~11^ADD~3-1[1]_output_0_0 ),
        .sumout(\adder_$add~11^ADD~3-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~11^ADD~3-2[1]  (
        .a(\adder_$add~11^ADD~3-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~11^ADD~3-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~11^ADD~3-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~9^ADD~4-0~dummy_output~0~1  (
        .a(\adder_$add~9^ADD~4-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~9^ADD~4-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~9^ADD~4-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~9^ADD~4-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~9^ADD~4-1[1]  (
        .a(\adder_$add~9^ADD~4-1[1]_input_0_0 ),
        .b(\adder_$add~9^ADD~4-1[1]_input_1_0 ),
        .cin(\adder_$add~9^ADD~4-1[1]_input_2_0 ),
        .cout(\adder_$add~9^ADD~4-1[1]_output_0_0 ),
        .sumout(\adder_$add~9^ADD~4-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~9^ADD~4-2[1]  (
        .a(\adder_$add~9^ADD~4-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~9^ADD~4-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~9^ADD~4-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~7^ADD~5-0~dummy_output~0~1  (
        .a(\adder_$add~7^ADD~5-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~7^ADD~5-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~7^ADD~5-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~7^ADD~5-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~7^ADD~5-1[1]  (
        .a(\adder_$add~7^ADD~5-1[1]_input_0_0 ),
        .b(\adder_$add~7^ADD~5-1[1]_input_1_0 ),
        .cin(\adder_$add~7^ADD~5-1[1]_input_2_0 ),
        .cout(\adder_$add~7^ADD~5-1[1]_output_0_0 ),
        .sumout(\adder_$add~7^ADD~5-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~7^ADD~5-2[1]  (
        .a(\adder_$add~7^ADD~5-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~7^ADD~5-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~7^ADD~5-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~5^ADD~6-0~dummy_output~0~1  (
        .a(\adder_$add~5^ADD~6-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~5^ADD~6-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~5^ADD~6-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~5^ADD~6-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~5^ADD~6-1[1]  (
        .a(\adder_$add~5^ADD~6-1[1]_input_0_0 ),
        .b(\adder_$add~5^ADD~6-1[1]_input_1_0 ),
        .cin(\adder_$add~5^ADD~6-1[1]_input_2_0 ),
        .cout(\adder_$add~5^ADD~6-1[1]_output_0_0 ),
        .sumout(\adder_$add~5^ADD~6-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~5^ADD~6-2[1]  (
        .a(\adder_$add~5^ADD~6-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~5^ADD~6-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~5^ADD~6-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~3^ADD~7-0~dummy_output~0~1  (
        .a(\adder_$add~3^ADD~7-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~3^ADD~7-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~3^ADD~7-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~3^ADD~7-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~3^ADD~7-1[1]  (
        .a(\adder_$add~3^ADD~7-1[1]_input_0_0 ),
        .b(\adder_$add~3^ADD~7-1[1]_input_1_0 ),
        .cin(\adder_$add~3^ADD~7-1[1]_input_2_0 ),
        .cout(\adder_$add~3^ADD~7-1[1]_output_0_0 ),
        .sumout(\adder_$add~3^ADD~7-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~3^ADD~7-2[1]  (
        .a(\adder_$add~3^ADD~7-2[1]_input_0_0 ),
        .b(1'bX),
        .cin(\adder_$add~3^ADD~7-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~3^ADD~7-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~8^ADD~11-0~dummy_output~0~1  (
        .a(\adder_$add~8^ADD~11-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~8^ADD~11-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~8^ADD~11-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~8^ADD~11-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~8^ADD~11-1[1]  (
        .a(\adder_$add~8^ADD~11-1[1]_input_0_0 ),
        .b(\adder_$add~8^ADD~11-1[1]_input_1_0 ),
        .cin(\adder_$add~8^ADD~11-1[1]_input_2_0 ),
        .cout(\adder_$add~8^ADD~11-1[1]_output_0_0 ),
        .sumout(\adder_$add~8^ADD~11-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~8^ADD~11-2[1]  (
        .a(\adder_$add~8^ADD~11-2[1]_input_0_0 ),
        .b(\adder_$add~8^ADD~11-2[1]_input_1_0 ),
        .cin(\adder_$add~8^ADD~11-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~8^ADD~11-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~10^ADD~12-0~dummy_output~0~1  (
        .a(\adder_$add~10^ADD~12-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~10^ADD~12-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~10^ADD~12-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~10^ADD~12-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~10^ADD~12-1[1]  (
        .a(\adder_$add~10^ADD~12-1[1]_input_0_0 ),
        .b(\adder_$add~10^ADD~12-1[1]_input_1_0 ),
        .cin(\adder_$add~10^ADD~12-1[1]_input_2_0 ),
        .cout(\adder_$add~10^ADD~12-1[1]_output_0_0 ),
        .sumout(\adder_$add~10^ADD~12-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~10^ADD~12-2[1]  (
        .a(\adder_$add~10^ADD~12-2[1]_input_0_0 ),
        .b(\adder_$add~10^ADD~12-2[1]_input_1_0 ),
        .cin(\adder_$add~10^ADD~12-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~10^ADD~12-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~12^ADD~13-0~dummy_output~0~1  (
        .a(\adder_$add~12^ADD~13-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~12^ADD~13-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~12^ADD~13-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~12^ADD~13-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~12^ADD~13-1[1]  (
        .a(\adder_$add~12^ADD~13-1[1]_input_0_0 ),
        .b(\adder_$add~12^ADD~13-1[1]_input_1_0 ),
        .cin(\adder_$add~12^ADD~13-1[1]_input_2_0 ),
        .cout(\adder_$add~12^ADD~13-1[1]_output_0_0 ),
        .sumout(\adder_$add~12^ADD~13-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~12^ADD~13-2[1]  (
        .a(\adder_$add~12^ADD~13-2[1]_input_0_0 ),
        .b(\adder_$add~12^ADD~13-2[1]_input_1_0 ),
        .cin(\adder_$add~12^ADD~13-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~12^ADD~13-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~14^ADD~14-0~dummy_output~0~1  (
        .a(\adder_$add~14^ADD~14-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~14^ADD~14-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~14^ADD~14-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~14^ADD~14-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~14^ADD~14-1[1]  (
        .a(\adder_$add~14^ADD~14-1[1]_input_0_0 ),
        .b(\adder_$add~14^ADD~14-1[1]_input_1_0 ),
        .cin(\adder_$add~14^ADD~14-1[1]_input_2_0 ),
        .cout(\adder_$add~14^ADD~14-1[1]_output_0_0 ),
        .sumout(\adder_$add~14^ADD~14-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~14^ADD~14-2[1]  (
        .a(\adder_$add~14^ADD~14-2[1]_input_0_0 ),
        .b(\adder_$add~14^ADD~14-2[1]_input_1_0 ),
        .cin(\adder_$add~14^ADD~14-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~14^ADD~14-2[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~16^ADD~15-0~dummy_output~0~1  (
        .a(\adder_$add~16^ADD~15-0~dummy_output~0~1_input_0_0 ),
        .b(\adder_$add~16^ADD~15-0~dummy_output~0~1_input_1_0 ),
        .cin(\adder_$add~16^ADD~15-0~dummy_output~0~1_input_2_0 ),
        .cout(\adder_$add~16^ADD~15-0~dummy_output~0~1_output_0_0 ),
        .sumout()
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~16^ADD~15-1[1]  (
        .a(\adder_$add~16^ADD~15-1[1]_input_0_0 ),
        .b(\adder_$add~16^ADD~15-1[1]_input_1_0 ),
        .cin(\adder_$add~16^ADD~15-1[1]_input_2_0 ),
        .cout(\adder_$add~16^ADD~15-1[1]_output_0_0 ),
        .sumout(\adder_$add~16^ADD~15-1[1]_output_1_0 )
    );

    adder #(
        .WIDTH(1'b1)
    ) \adder_$add~16^ADD~15-2[1]  (
        .a(\adder_$add~16^ADD~15-2[1]_input_0_0 ),
        .b(\adder_$add~16^ADD~15-2[1]_input_1_0 ),
        .cin(\adder_$add~16^ADD~15-2[1]_input_2_0 ),
        .cout(),
        .sumout(\adder_$add~16^ADD~15-2[1]_output_1_0 )
    );


endmodule
